"""add phone

Revision ID: 4671c86805a1
Revises: 76aa15b301f8
Create Date: 2021-11-22 12:41:06.582887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4671c86805a1'
down_revision = '76aa15b301f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
